server:
  port: 8761
 
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

      

#server:
#  port: 8761
#spring:
#  profiles: localhost
#  application:
#    name: eureka-server
#eureka:
#  instance:
#    hostname: localhost
#  client:
#    serviceUrl:
#      defaultZone: http:///${eureka.instance.hostname}:8762/eureka/
#  
#
#server:
#  port: 8762
#spring:
#  profiles: localhost
#  application:
#    name: eureka-server
#eureka:
#  instance:
#    hostname: localhost
#  client:
#    serviceUrl:
#      defaultZone: http:///${eureka.instance.hostname}:8761/eureka/
